### ISSUE TITLE
Suggestion: Enable Travis to check in macOS

### ISSUE THREAD

**Issue by Neves-P** [Giappo/jap#16]
So that us lowly non-mac users can check if the package builds also on gentrified neighborhoods, it would be nice to have a travis build for linux and mac. 

I took the liberty of adding a .yml on my branch which can easily be merged to `develop` and `master`. Could you please enable the travis build on your account and merge (or I can merge myself once enabled).

**Comment by Giappo** [comment]
@Neves-P  feel free to push on develop if you have good reasons that it will not break anything, like in this case

**Comment by Neves-P** [comment]
Thanks, did so now!
Package builds in linux and mac now: https://travis-ci.com/github/Giappo/jap/jobs/326267705
