### ISSUE TITLE
Vignette building clogs Rcheck :(

### ISSUE THREAD

**Issue by Giappo** [Giappo/jap#24]
ctrl + E leads to utter sadness. Vignettes take centuries to build. Probably it cannot deal with the jobs trick

**Comment by Neves-P** [comment]
Indeed... I increased the `R CMD build` time in the .yml here: a2cf210956fc969900aa4cd9f4b82c734f99967b to see if it at least builds, but it's a brute force workaround, not a solution...

**Comment by Neves-P** [comment]
I tried tackling this here: 4745eb7aad9cc67c849d29b1f894847911071e75 but I just made the vignettes not build at all. @Giappo, if your 149165f fix is better I can revert mine
