### ISSUE TITLE
Bug: Saved files on /data partition go onto jap_scripts folder, not Projects/results

### ISSUE THREAD

**Issue by Neves-P** [Giappo/jap#31]
On the trial runs I'm doing now I notice that upon saving the output it's being placed in the jap_scripts folder, most likely because that becomes the R working directory. I've checked, and in `sls` this is done by a [save function](https://github.com/Giappo/sls/blob/0ecf52e39509de9867e2dbedc887d56e191b93b2/R/sls_main_utils.R#L45) that has the same folder structure built in. This seems redundant, as the point of the folder handling in `jap` should take care of this.

Perhaps we could address this by changing the wd while the pipelines run to be `/home/$USER/` or `/data/$USER/` or something similar, depending on user choice. That way a `save()` call in the pipeline would have access to the `~/Projects/$PROJECT/results/` path easily. 
What do you think? Maybe we can do this with just a simple call to `cd` on `run_on_cluster.bash`.

**Comment by Giappo** [comment]
I think it is a good idea.
What if I code it and you test it?

**Comment by Neves-P** [comment]
Yeah, sure! Thanks a bunch! 🚀
