### ISSUE TITLE
Read default arguments from .Rprofile

### ISSUE THREAD

**Issue by TheoPannetier** [Giappo/jap#36]
The new set of `default_X` functions allows the user to input their choices, and store them in the .Rprofile.
As of now, `default_X` functions are asking for user input every time they are called, even if there is already a user choice saved in .Rprofile, in which case they just append a line, and the choice then has duplicate entries in .Rprofile.
It would be great to make the functions detect if there is already a corresponding entry in .Rprofile, and if yes, return it so that default choices can be automatically passed to other `jap` functions.

**Comment by Giappo** [comment]
I don't understand.
The functions are already meant to work in this way:
<img width="913" alt="Screenshot 2020-05-03 16 18 43" src="https://user-images.githubusercontent.com/14541948/80916595-fe85aa80-8d59-11ea-9c43-74c6d2a2ad54.png">

**Comment by Giappo** [comment]
The only thing I can think of is that there are problems when using an apple OS

**Comment by Neves-P** [comment]
I believe the duplicated lines in `.Rprofile` are created by successive runs of `jap::initialize_jap()`, rather than the `default_X` family of functions. At least that's the behavior I observe on my end.

**Comment by Giappo** [comment]
It's not possible, because every time initialize_jap is run the questions are asked only if those variables are not already present in the Rprofile file.
I suggest you run jap::edit_profile, you delete all the content in the file and the run jap::initialize_jap again.

**Comment by Neves-P** [comment]
I see. Then in that case it could happen if a user exits `jap::initialize_jap()` before the function has ended? I tested running again and indeed I get just a suggestion to run `jap::edit_profile()` (which btw is failing on R 4.0 windows, opening an issue now). I got no change of duplicated lines in `initialize_jap()`, so that's good :+1:

**Comment by TheoPannetier** [comment]
I've emptied .Rprofile and filled it again with `initialize_jap()`. Works perfectly well now!

**Comment by TheoPannetier** [comment]
Running `initialize_jap()` multiple times does not add duplciated entries to .Rprofile
