### ISSUE TITLE
edit_profile() fails in Windows R 4.0

### ISSUE THREAD

**Issue by Neves-P** [Giappo/jap#37]
Running `jap::edit_profile()` fails under Windows for R version 4.0.0.
The cause is the call to `rappdirs::app_dir()$os`

``` r
rappdirs::app_dir()$os
#> [1] "win"
```

The package checks for `"windows"`. @Giappo, can you please confirm if you get `"windows"` or "`win"` on your side? I'm guessing this changed when going from 3.6.3 -> 4.0.0, if you are running 3.6.x it probably still runs so an easy fix that pleases everyone would be checking the string for `"win"` and `"windows"`, I'd be happy to change that.

**Comment by Giappo** [comment]
I will fix this

**Comment by Giappo** [comment]
@TheoPannetier and @Neves-P try again and see if it works

**Comment by TheoPannetier** [comment]
It works fine on MacOS with R 4.0

**Comment by TheoPannetier** [comment]
My bad, didn't mean to close issue

**Comment by Giappo** [comment]
Is there anything that still needs a fix?

**Comment by TheoPannetier** [comment]
@Neves-P, close the issue of not 😉

**Comment by Neves-P** [comment]
Yup, works here, thanks! 🌈
