### ISSUE TITLE
Bug: Functions not running on cluster due to jap:: namespace

### ISSUE THREAD

**Issue by Neves-P** [Giappo/jap#41]
At the moment the functions I run on the cluster are not running, due to this error, found in the log file: 
``` r
Error in loadNamespace(name) : there is no package called ‘jap’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```
As far as I can tell, this arises from the call of `run_functions` or another similar function call, such as here: https://github.com/Giappo/jap/commit/2175425564800b73325db9d816be6d5091903112#diff-dfac0e28e7132865889d96bcaed539dbR267

I see here that the namespace is called explicitly from this commit onward, when it wasn't before. I can't say for sure, but I suspect that this is what's causing the issue. I haven't changed it as to test it out I will need to push this to `master`. Is there any reason to call `jap::` here? @Giappo, are you able to submit jobs that run at the moment?

**Comment by Neves-P** [comment]
I've verified here: 2c2923f that removing `jap::` from calls to `run_function()` and `run_function_from_file()` makes the jobs run on Peregrine. Is there any reason not to leave it in this way?

**Comment by Giappo** [comment]
I think it's because you don't call the functions from the package but from the function file we upload to the cluster. This is because jap cannot be installed on cluster but we still need those functions. I added the jap:: just because it's a strong habit I have but it was a mistake.
 Is it working now?

**Comment by Neves-P** [comment]
Right, thanks! It is working on my branch after having removed the `jap::` parts, I just didn't want to push right away to develop/master because it could have been added for another reason. In that case it's fixed, I'll merge to `develop` and if it builds I'll merge to `master` :+1:

**Comment by Neves-P** [comment]
Done! Let me know / reopen issue if something is still not working 🌈
