### ISSUE TITLE
Lint package?

### ISSUE THREAD

**Issue by TheoPannetier** [Giappo/jap#8]
I have an issue with ` lintr::expect_lint_free()` in `test-style.R`.
It fails when I run tests, returning the output of `lintr::lint_package()`, and when I run it directly on console I get `Error: Reason: On CRAN`
Is it supposed to check that everything is linted, or that there is no in-code lint statements?

**Comment by Neves-P** [comment]
`expect_lint_free()` will fail the test if there is something still to be linted (including cyclomatic complexity) as far as I know. You can run the default lint checker locally by calling ```lintr::lint_package()``` if you want to see what fails.

**Comment by Giappo** [comment]
Honestly, I don't really want to lint everything. It takes a lot of time and it's not really worth it. I can try to write in a decent style without having lint bitching about it...

**Comment by TheoPannetier** [comment]
I'm ok with that; lint can be an unecessary hassle.
But then I would just remove this test, are you ok with that?

**Comment by Giappo** [comment]
Yeah, just remove it. In case there will be problems for which is necessary to lint I will reintroduce it with the right settings.

**Comment by thijsjanzen** [comment]
I just ran into this bug/error as well. It is caused by the function 'testthat::skip_on_cran()".

I suspect it only gives errors locally, and perhaps not on Travis?
